name: 'Run Sobelow'
description: 'A custom action to run Sobelow security analysis'
inputs:
  working-directory:
    description: 'The directory to run Sobelow in'
    required: false
    default: '.'
runs:
  using: 'docker'
  image: 'elixir:latest'
  steps:
    - name: Install dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Run Sobelow
      run: |
        mix sobelow --exit --format json --out ${{ github.workspace }}/sobelow-output.json
