name: 'Run Sobelow'
description: 'A custom action to run Sobelow security analysis'
inputs:
  working-directory:
    description: 'The directory to run Sobelow in'
    required: false
    default: '.'
runs:
  using: 'composite'
  steps:
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        otp-version: '27'
        elixir-version: '1.17.2'
    - name: Install dependencies
      run: |
        mix archive.install hex sobelow --force
        mix deps.get
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - name: Run Sobelow
      run: |
        mix sobelow --exit --format json --out ${{ github.workspace }}/sobelow-output.json
      shell: bash
      working-directory: ${{ inputs.working-directory }}
