name: 'Run Sobelow'
description: 'A custom action to run Sobelow security analysis'
inputs:
  working-directory:
    description: 'The directory to run Sobelow in'
    required: false
    default: '.'
runs:
  using: 'composite'
  steps:
    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        otp-version: '23.x'
        elixir-version: '1.11.x'
    - name: Install dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
      working-directory: ${{ inputs.working-directory }}
    - name: Run Sobelow
      run: |
        mix sobelow --exit --format json --out ${{ github.workspace }}/sobelow-output.json
      working-directory: ${{ inputs.working-directory }}
