name: Snyk Monitor Repositories

on:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight
  workflow_dispatch: # Allows manual triggering

jobs:
  snyk-monitor:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: [
          'alexwang-trr/elixir-sandbox',
          'alexwang-trr/spring-boot-hello-world',
          'trr-infosec-sandbox/elixir-testing-neeraj'
        ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: ${{ matrix.repo }}
          token: ${{ secrets.TOKEN_GITHUB }}
          fetch-depth: 0

      - name: Check for Elixir files
        id: check-elixir
        run: |
          if ls *.ex* 1> /dev/null 2>&1; then
            echo "found=true" >> $GITHUB_ENV
          else
            echo "found=false" >> $GITHUB_ENV
          fi

      - name: Set up Elixir
        if: env.found == 'true'
        uses: erlef/setup-beam@v1
        with:
            otp-version: '27'
            elixir-version: '1.17.2'

      - uses: snyk/actions/setup@master
      - name: Set up Snyk CLI
        run: |
            snyk monitor --org=security-sandbox
        env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
