name: Snyk PR Check

# Trigger the workflow on pull request events
on: [pull_request]

jobs:
  snyk-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Elixir
        uses: actions/setup-elixir@v1.5.0
        with:
          otp-version: '23.x'
          elixir-version: '1.11.x'

      - name: Install dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
        working-directory: .

      - name: Run Sobelow
        run: |
          mix sobelow --exit --format json --out ${{ github.workspace }}/sobelow-output.json
        working-directory: .