name: Snyk PR Check

# Trigger the workflow on pull request events
on: [pull_request]

jobs:
  snyk-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Run Snyk Test
      #   env:
      #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      #     SNYK_ORG: ${{ secrets.SNYK_ORG }}
      #   run: |
      #     docker run --rm \
      #       -v "${{ github.workspace }}:/project" \
      #       -w /project \
      #       -e SNYK_TOKEN="${{ secrets.SNYK_TOKEN }}" \
      #       snyk/snyk:elixir snyk test --file=mix.exs --org=${{ secrets.SNYK_ORG }} | tee snyk-output.log
        continue-on-error: false

      - name: Run Sobelow Action
        uses: ./.github/sobelow
        with:
          working-directory: .
        continue-on-error: false