name: Snyk PR Check

# Trigger the workflow on pull request events
on: [pull_request]

jobs:
  snyk-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Snyk Test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          SNYK_ORG: ${{ secrets.SNYK_ORG }}
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/project" \
            -w /project \
            -e SNYK_TOKEN="${{ secrets.SNYK_TOKEN }}" \
            snyk/snyk:elixir snyk test --file=mix.exs --org=${{ secrets.SNYK_ORG }} | tee snyk-output.log
        continue-on-error: false

  sobelow-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Sobelow
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          mix sobelow --exit --format json --out sobelow-output.json
        continue-on-error: false