name: Snyk PR Check

# Trigger the workflow on pull request events
on: [pull_request]

jobs:
  snyk-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Sobelow Action
        uses: ./.github/sobelow
        with:
          working-directory: .
        continue-on-error: false

      - name: Run Snyk Action
        uses: ./.github/snyk
        with:
          working-directory: .
        continue-on-error: false